package:
  name: locanmf
  version: "1.1.1"

source:
  path: ../

build:
  number: 1
  
requirements:
  build:
    - python={{ python }}
    - numpy=1.16
    - scipy
    - scikit-learn
    - matplotlib
    - mkl
    - mkl-include
    - pytorch
    - torchvision
    - jupyterlab

  run:
    - python={{ python }}
    - numpy=1.16
    - scipy
    - scikit-learn
    - matplotlib
    - mkl
    - mkl-include
    - pytorch
    - torchvision
    - jupyterlab

test:
  imports:
    - locanmf.LocaNMF

about:
  home: https://github.com/ikinsella/locaNMF
  license: GPL
  license_family: GPL3
  license_file: LICENSE
